name: maven Github Action
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: run test for maven
    runs-on: ubuntu-latest
    steps:
      - name: get source code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: runing tests
        run: mvn test
  
  build:
    needs: test
    name: building maven
    runs-on: ubuntu-latest
    steps:
      - name: get source code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: building jarfile
        run: mvn clean package
      - name: upload argifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifact-data
          path: '**/target/*.jar'

    

    